services:
  redis:
    image: redis:7-alpine
    container_name: coderunner-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: coderunner-postgres
    environment:
      POSTGRES_USER: coderunner
      POSTGRES_PASSWORD: coderunner
      POSTGRES_DB: coderunner
    ports:
      - "5432:5432"

volumes:
